# yamllint disable rule:line-length
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt install -y lftp

      - name: Mirror
        run: |
          lftp \
            -e 'set ssl:verify-certificate false ; mirror --delete --transfer-all --reverse --verbose=1 ./FOLDER . ; quit' \
            -u '${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }}' \
            'ftp://${{ secrets.FTP_URL }}'
