name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - requirements.txt
      - sources/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install dependencies
        run: |
          sudo apt install -y lftp
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: Generate
        run: ./build.sh
      - name: Setup SSH
        # Prevent "Fatal error: Host key verification failed"
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SFTP_URL }} >> ~/.ssh/known_hosts
      - name: Automation
        # Mirror the locally generated website to the production server
        run: |
          lftp \
            -e 'mirror --delete --transfer-all --reverse --verbose=1 ./luma ${{ secrets.SFTP_PATH }} ; quit' \
            -u '${{ secrets.SFTP_USER }},${{ secrets.SFTP_PASSWORD }}' \
            sftp://${{ secrets.SFTP_URL }}
