# yamllint disable rule:line-length
name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - requirements.txt
      - sources/**
  workflow_dispatch:

concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip
      - name: Install dependencies
        run: |
          sudo apt install -y lftp
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: Generate
        run: ./build.sh
      - name: Mirror
        run: |
          lftp \
            -e 'set ssl:verify-certificate false ; mirror --delete --transfer-all --reverse --verbose=1 ./luma . ; quit' \
            -u '${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }}' \
            ftp://${{ secrets.FTP_URL }}
