name: Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install dependencies
        run: |
          sudo apt install -y aspell-fr
          python -m pip install -U pip
          python -m pip install -r requirements-tests.txt
      - name: Checks
        run: ./checks.sh
